export const ADD_HISTORY= 'ADD_HISTORY';
export const USER_LOGIN= 'USER_LOGIN';
export const ADD_LEADERBOARD= 'ADD_LEADERBOARD';
export const ADD_NEWS= 'ADD_NEWS';
export const ADD_TOURNAMENTS= 'ADD_TOURNAMENTS';